version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/kawasin73/htask

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - run:
          name: installing go-junit-report
          command: go get -u github.com/jstemmer/go-junit-report

      - checkout

      - run:
          name: running scheduler tests
          command: |
            mkdir -p $TEST_RESULTS
            trap "go-junit-report <${TEST_RESULTS}/scheduler.out > ${TEST_RESULTS}/scheduler-test-report.xml" EXIT
            go test -v -race | tee ${TEST_RESULTS}/scheduler.out

      - run:
          name: running cron tests
          command: |
            mkdir -p $TEST_RESULTS
            trap "go-junit-report <${TEST_RESULTS}/cron.out > ${TEST_RESULTS}/cron-test-report.xml" EXIT
            go test -v -race ./cron | tee ${TEST_RESULTS}/cron.out

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
